### ISSUE TITLE
robots.txt 생성

### ISSUE THREAD

**Issue by jisoo449** [injaecode/chijin_final#10]
### 관련 항목
- 3-5 검색엔진 정보 노출 가능성

### 해결방법
- robots.txt는 정적 파일이므로  webapp 경로에 저장하였다.

**Comment by zimza1abim** [comment]
[robots.txt](https://github.com/injaecode/chijin_final/files/14337941/robots.txt)

**Comment by jisoo449** [comment]
참고중:[ https://github.com/spring-projects/spring-boot/issues/33499](#https://github.com/spring-projects/spring-boot/issues/33499)

**Comment by jisoo449** [comment]
다시 #20 문제 발생
