### ISSUE TITLE
[조치] 도메인 발급 및 ssl 인증서 적용

### ISSUE THREAD

**Issue by jisoo449** [injaecode/chijin_final#14]
### 관련 항목
- 5-2 요청 및 응답 값 내 주요정보 포함여부 확인

**Comment by jisoo449** [comment]
지금까지 찾은 방법은 두 가지임
1.  ELB에서 등록
2. Amazon CloudFront 사용

**Comment by jisoo449** [comment]
https://support.bespinglobal.com/ko/support/solutions/articles/73000544834--aws-acm-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EB%B0%9C%EA%B8%89-%ED%9B%84-%EC%A0%81%EC%9A%A9-%EB%B0%A9%EB%B2%95-  
위 사이트 내용을 토대로 정리하자면, 지금까지는 인증서 발급, 등록을 한 것이고 이를 적용 해 주어야 한다.  
acm에서 발급한 인증서는 aws 내에서 호스팅 하는 서비스에만 적용이 가능하며, 인스턴스 내에서 구동 중인 어플리케이션 서비스에는 적용할 수 없다.

**Comment by zimza1abim** [comment]
### 1. 도메인 발급
#### 1-1 Route 53
도메인 구매 > 도메인 등록 (약10분 소요) > 호스팅 영역 > 등록 도메인 선택 > 호스팅 영역 > 레코드 생성 > 단순 라우팅 > 단순 레코드 정의 > 레코드 유형 A선택 > 엔드포인트 로드밸런싱 선택 > 리전 (서울)

### 2. SSL 인증서 발급
#### 2-1. ACM
인증서 요청 > 퍼블릭 인증서 요청 > 도메인 입력 > RSA 2048 알고리즘 > 요청 > 발급 대기 > 발급 완료 후 인증서 ID 선택 > Route 53에서 레코드 생성 선택 

### 3. 로드밸런서 설정
#### 3-1. EC2 로드밸런싱
리스너 및 규칙 HTTP/80, HTTPS/443 추가 > HTTPS/443 추가시 발급한 인증서 선택
