### ISSUE TITLE
[조치] java response 패킷 정보 수정

### ISSUE THREAD

**Issue by jisoo449** [injaecode/chijin_final#16]
- res 패킷 헤더에 서버 정보 삭제

<br/><br/>

### sk 항목
- 7-3 서버 헤더 정보 노출

**Comment by jejumandarin00** [comment]
Cloud 상에서 nginx 설정 변경함.

1. server_tokens off 주석 해제
2. nginx.conf 파일에 proxy_pass_Header Server; 적어서 현재 nginx 버전 정보 아닌 Server로 나옴.

참고
https://myhappyman.tistory.com/249
