### ISSUE TITLE
[Trouble-Shooting]프로젝트 실행 시 Server Timeout 발생

### ISSUE THREAD

**Issue by jisoo449** [injaecode/chijin_final#20]
## 설명
서버 실행 시 server timeout 문제 발생
![image](https://github.com/injaecode/chijin_final/assets/48276691/752a4ebc-d6c8-4c36-9416-6ec7314dc05b)  

```sql
Server Tomcat v9.0 Server at localhost was unable to start within 45 seconds. If the server requires more time, try increasing the timeout in the server editor.
```

<br/><br/>

## 해결 방법
실행과 중단을 반복하다 보면 중간에 데이터 및 설정이 꼬이는 경우가 발생한다.  
이를 해결하기 위해서는 프로젝트 clean, refresh 이후 에디터를 재시작 해야 한다.  

<br/><br/>

## 동일한 원인으로 발생 가능한 문제
- #23
- #24

**Comment by jisoo449** [comment]
디버깅 했는데 다음 메시지가 나오고 멈춤. 아마 데이터베이스 불러오는 과정에서 문제가 생긴 듯?  

```
2024-02-20 11:50:10,092 DEBUG [stu.common.logger.LoggerInterceptor] ======================================          START         ======================================
2024-02-20 11:50:10,093 DEBUG [stu.common.logger.LoggerInterceptor]  Request URI 	:  /mainList.do;jsessionid=922F3F8A219473660D969EA700C2D59B
2024-02-20 11:50:10,096 DEBUG [stu.common.dao.AbstractDao] 	 QueryId 	: goods.newGoodsList
```

**Comment by injaecode** [comment]
로컬 디비 비밀번호로 바꾸고 연결해봐요

**Comment by jisoo449** [comment]
비밀번호  DNFLRKskadlrk#1로 수정했는데도 데이터 못불러와요ㅠㅜㅠ

**Comment by jisoo449** [comment]
저는 서버 타임아웃 문제는 해결됐어요. 이유는 모르겠삼...

**Comment by jisoo449** [comment]
서버 설정 중 server  modules without publishing 체크하니까 뭔가 바뀜  
![image](https://github.com/injaecode/chijin_final/assets/48276691/4678b71a-bd10-4e5d-b2d2-ec780dec4471)  
![image](https://github.com/injaecode/chijin_final/assets/48276691/db56b746-0d53-4a74-b860-d90429962327)
